spring:
  application:
    name: teste-poc-web
  profiles:
    active: local

version: $project.version$

---
spring:
  profiles: local

cassandra:
  contactpoints: 127.0.0.1
  port: 9042
  keyspace: testepoc


---
spring:
  profiles: docker

cassandra:
  contactpoints: ${CASSANDRA_HOST}
  port: ${CASSANDRA_PORT}
  keyspace: ${CASSANDRA_KEYSPACE}
